### ISSUE TITLE
request for connection

### ISSUE THREAD

**Issue by ShockYoungCHN** [nannoda/exchange-rate-bot#1]
I am interested in systems & rust, also an OL contributor. Would like to connect with you if you don't mind.

**Comment by yamada-sexta** [comment]
how do you like to connect?

**Comment by ShockYoungCHN** [comment]
> how do you like to connect?

telegram if u prefer anonymity (https://t.me/samurai1024), or just email (yuanzhuoyang@gmail.com)?
